language: cpp
script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TESTS=1 ..
  - make
  - make test
compiler:
  - clang
before_install:
  - sudo apt-get update
  - sudo apt-get install libboost1.48-all-dev libglm-dev
